apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:dbsd8i237Uk=,iv:BwAAluQt2oYyMVhFCMgnwteQB0zvKByZUMVHVP4Ki5w=,tag:HrBbvhO9ZJkWbuyWu/WZFQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:2TTYCIuQo/7at7/i,iv:edBBnfFtYlVwFN/RiWG/c6EH2psceDIo3XM4N7Vyy9c=,tag:ICqx1ekynLFA/Bq59qsnLA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age19ss5jzct6wh3ds48zj80wtv24nqyrl9e084d6eky63ama39q5ffqq02axk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVGQ2R1c2MGo2ZzJBbjVw
            SEc3azFYYlc3MERXaVI4eGF6ZWNTS1RrUFZnCjQwTCs0dmV1RExPUGR6am9IWkkw
            R25hcVNKNWpURDlLSnFBRDU3L0ppRncKLS0tICtBaXdHOFhRRGpsNjIzRzNXTFpB
            dExaa08ySy9UdGRSSkdndkNlYStYR2MKGfe1Gy/V6NHDHVROML9q1N2OCG6VG55y
            WYH3agCtmmsPIIS+UN2U1INZfXBnq4UumBEAnrxmwJ3ownS/AgKygA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T14:37:54Z"
    mac: ENC[AES256_GCM,data:IrgUL7aieNKvyefug7EO63Jx1zWkSsK953qjLl+lxgJ6hEhRqGu6G8xe/GfwNF4WSXChcao1AeikmRkD08kCAG1nMFxFgzVsjOKajaVdZ7XKO/xwC6X4eNRCXiFthiViaPru9P3pD0acD9kigO2JZ49pp2ehh/BvApP2AjNPPd0=,iv:MSPSwBtjT7EBn8YENs6wFpwftExzka6zokEZ5kqxAec=,tag:UmoV5L18h5APFUUV+9dGag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
