apiVersion: v1
data:
    password: ENC[AES256_GCM,data:HOUZUg==,iv:NAMEa7FM/M4mnOXTfhGQgJgNzq8jQR1wiAoITecULPA=,tag:TBEdXJbS6H77mkkN0qfX7Q==,type:str]
    user: ENC[AES256_GCM,data:0uL3Od7nA/M=,iv:aiUXz71XJjxTvTleQaxhoUnZmbtmb8scI7KT+eploYM=,tag:uu/1tQivDhfLv2L1/8efhA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    age:
        - recipient: age19ss5jzct6wh3ds48zj80wtv24nqyrl9e084d6eky63ama39q5ffqq02axk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByampMYzMyZUhvakNVdWht
            WHcrNVYyaGJUbEhwSHRXaEY0cGNYcStlTlZrCk05eXdVeFpLckIyVW1nV0EwRUhO
            VVJ5dm5QMVdGYnRFcDBKNFVIQWZzU1EKLS0tIG45ZkJzWElkMUpPZ3RJS1B0WHRz
            bHZHSGFYTm9KNlkwTWJkUGZDY2xuZ3MK+oNBfuORbX2rIxeB3zQMnFvRbLQk8qD/
            XcS0YSApuqZHqgkuOU4GRYrQatefdeW74OOUbi9Xtx/L07CjdE/9TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-22T16:21:35Z"
    mac: ENC[AES256_GCM,data:jpWB22DD+bO5XmSawKJ+/7ZIL7bCpqxQ/4TkUYCIY2cbH8LAugh/1vD1s2MlREYD8+0WC60pz/NGJBQfA2HsBMjVFFvgZyvYwSEwNcKXcfeJdYjKBMURPqH+6eR1CF5AkbJ221NxxbWHUekjCXHz6fzqfB80n+VlX+ZyxXwD75c=,iv:1YIQ2G6+Ry4ThJWQ/hYogvhbtLCgyxkW8J6vBZk8fSk=,tag:0WgZPMBPTP3YfFDkW48VcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
