apiVersion: v1
kind: Service
metadata:
  name: linkding
spec:
  ports:
    - port: 9090 #Correspond to the container port that is exposedd in deployment.yaml
  selector:
    app: linkding # This should match the label in the deployment.yaml
  type: ClusterIP
