apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "@hourly" # This cronjob will run every hour.
  concurrencyPolicy: Forbid # It prevents overlapping executions. It's prevents two cronjobs from running at the same time.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:latest
              args:
                - luddera/pi-cluster # This is the repository to renovate. My repository.

              envFrom:
                - secretRef:
                    name: renovate-container-env
                - configMapRef:
                    name: renovate-configmap

          restartPolicy: Never